# Generated by Django 6.0 on 2025-12-26 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semantic', '0002_add_initial_semantic_concepts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spent_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semantic_concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='semantic.semanticconcept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
