# Generated by Django 6.0 on 2025-12-26 08:43

from django.db import migrations


def create_initial_semantic_concepts(apps, schema_editor):
    SemanticConcept = apps.get_model("semantic", "SemanticConcept")

    initial_concepts = [
        ("food_packaged_snacks", "Packaged snack foods like chips, wafers, namkeen"),
        ("food_meals", "Cooked meals such as lunch, dinner, tiffin"),
        ("food_groceries", "Household grocery items like rice, wheat, pulses"),
        ("food_dairy", "Milk and dairy products"),

        ("transport_auto", "Local transport such as auto-rickshaw"),
        ("transport_bus", "Bus travel expenses"),
        ("transport_taxi", "Taxi or cab services like Uber, Ola"),

        ("utilities_electricity", "Electricity bill payments"),
        ("utilities_gas", "Cooking gas or LPG cylinder"),
        ("utilities_water", "Water-related bills"),

        ("health_medicine", "Medicines and basic healthcare expenses"),
        ("education_fees", "School or college fees"),
    ]

    for semantic_id, description in initial_concepts:
        SemanticConcept.objects.get_or_create(
            semantic_id=semantic_id,
            defaults={"description": description}
        )

class Migration(migrations.Migration):

    dependencies = [
        ("semantic", "0001_initial"),  # this might be 0001 or something else in your app
    ]

    operations = [
        migrations.RunPython(create_initial_semantic_concepts),
    ]
